# -*- coding: utf-8 -*-
"""全局常量模块。"""
from .global_constants import (
    HTTP_TIMEOUT_DEFAULT,
    HTTP_TIMEOUT_FAST,
    RETRY_MAX_DEFAULT,
    RETRY_BACKOFF_BASE,
    RING_EXEC_TIMEOUT_DEFAULT,
    HITL_GATE_RINGS,
    WANFANG_TRUST_RULES,
    WANFANG_MAX_LIMIT,
    WANFANG_MSG_NOT_FOUND,
    WANFANG_MSG_DISCIPLINE_NO_NAME,
)

__all__ = [
    "HTTP_TIMEOUT_DEFAULT",
    "HTTP_TIMEOUT_FAST",
    "RETRY_MAX_DEFAULT",
    "RETRY_BACKOFF_BASE",
    "RING_EXEC_TIMEOUT_DEFAULT",
    "HITL_GATE_RINGS",
    "WANFANG_TRUST_RULES",
    "WANFANG_MAX_LIMIT",
    "WANFANG_MSG_NOT_FOUND",
    "WANFANG_MSG_DISCIPLINE_NO_NAME",
]
